version: '3'
networks:
    inception:
        driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/atourret/data/wp_data

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/atourret/data/mariadb_data

services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        ports:
            - 3306:3306
        env_file: .env
        volumes:
            - mariadb_data:/var/lib/mysql
        restart: always
        networks:
            - inception

    wordpress:
        depends_on:
            - mariadb
        build: ./requirements/wordpress
        container_name: wordpress
        ports:
            - 9000:9000
        env_file: .env
        volumes:
            - wp_data:/var/www/
        restart: always
        networks:
            - inception

    nginx:
        depends_on:
            - wordpress
        build: ./requirements/nginx
        container_name: nginx
        ports:
            - 443:443
        volumes:
            - wp_data:/var/www/
        restart: always
        networks:
            - inception
